### PR TITLE
added 2 contexts with an example file for demo purpose

### PR DESCRIPTION
**Pull request by junpark77**

### CODE REVIEW

**Review by tonyjly — DISMISSED** [review]

**Review by brentonhershner — CHANGES_REQUESTED** [review]
"This branch has conflicts that must be resolved."
Can you resolve the conflicts first? I'm guessing you didn't pull down the latest from the repo before pushing it up.

**Comment by junpark77** [comment]
Conflicts resolved using github editor

**Comment by brentonhershner** [comment]
Except now it seems to fail to build. 😕

**Comment by junpark77** [comment]
not anymore. had 2 same imports

**Review by brentonhershner — DISMISSED** [review]
Awesome. Much better.

**Review by tonyjly — DISMISSED** [review]

**Comment by tonyjly** [comment]
Approved, but looks like some conflicts still exist that prevent rebasing. Can we fix the conlicts?

**Review by tonyjly — CHANGES_REQUESTED** [review]
Looks like `<<<<<<< HEAD` was added to Home.js, so CircleCI doesn't pass. Other code appears to be great though

**Review by tonyjly — APPROVED** [review]

**Pull request closed without merging**
